---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dijitalu/public_html/wp-content/themes/ikizler-bale-wordpress-theme
    - /bin/mkdir -p 
    - /bin/cp -R assets 
    - /bin/cp -R inc 
    - /bin/cp -R parts 
    - /bin/cp -R patterns 
    - /bin/cp -R templates 
    - /bin/cp style.css 
    - /bin/cp theme.json 
    - /bin/cp functions.php 
    - /bin/cp readme.md 